### ISSUE TITLE
How to scale this set-up.

### ISSUE THREAD

**Issue by bhanuc** [eladelrom/roomsjs#2]
Looks like an awesome module but lacks any documention on scaling it to multiple instances/machines. Any help in this regard would be very nice. Thanks

**Comment by eladelrom** [comment]
This is built to scale. You can use this code on multiple node instances and clients.  Internal node machines can communicate to each other via WebSocket, also multiple users (clients) can communicate and create multiple rooms.  I have added an example here: roomsjs-client/client/examples/collaborate.  I will soon add an example to communicate between two diff node machines and clients.
