### ISSUE TITLE
can i store joined room users?

### ISSUE THREAD

**Issue by MahdiPishguy** [eladelrom/roomsjs#3]
This library can store connected users which they are joined on rooms?

**Comment by eladelrom** [comment]
finally getting around to update this library.  I added code to be able to integrate an internal robot to listen to rooms messages.  From nodejs you can create a robot that will be registered as a user and listen to all messages:

<pre>
// Internal Robot connects to room and send data to all collaborate users
let messagetype = require('./node_modules/roomsjs/lib/enums/messagetype.js');
let robotMsgCallback = (type, data) => {
    console.log('robotMsgCallback :: type: ' + type + '' + ', data: ' + JSON.stringify(data));
};

setTimeout(function(){
    console.log('-------- joinRoom -------- ');
    rooms[messagetype.JOIN_ROOM]({
        'roomName': 'tester',
        subscriptions : {
            RoomInfoVO : true,
            ClientVO : true
        }
    });

    rooms[messagetype.REGISTER]({
        'roomName': 'tester',
        'userId' : 'robot',
        isRobot: true,
        robotMsgCallback: robotMsgCallback
    });

    setTimeout(function(){
        console.log('-------- store change -------- ');
        rooms[messagetype.STORE_STATE]({"roomName":"tester","name":"ClientVO","vo":{"clientId":"robot","mouseX":0,"mouseY":0,"comment":"","isDrag":true},"userId":"robot"});
    }, 5000);


    setTimeout(function(){
        console.log('-------- disconnect -------- ');
        rooms[messagetype.DISCONNECT]('robot');
    }, 10000);

}, 5000);
</pre>

A complete working example is here:  roomsjs-client/client/examples/collaborate

Additionally, you can listen to all connected messages via the server you create;

<pre>
let messagetype = require('./node_modules/roomsjs/lib/enums/messagetype.js');
let listenToP2PServerMessage = () => {
    server.on(messagetype.CONNECTION, function(ws) {
        console.log('listenToP2PServerMessage :: connected');
    });
    console.log('listenToP2PServerMessage :: listening websocket p2p');
};
listenToP2PServerMessage();
</pre>
