### ISSUE TITLE
Cannot npm install on Windows 10

### ISSUE THREAD

**Issue by vgriffin** [eladelrom/roomsjs#4]
I'm getting C++ compile errors that seem to be related to very old versions of dependency modules. (Some are > 4 years old.) I've installed a version that uses current versions of dependencies just to get something I can use as a starting point. I know that I cannot do rigorous testing with what I've got, but....

**Comment by eladelrom** [comment]
Feel free to update and make a pull request and I will include your changes.

**Comment by eladelrom** [comment]
no information regarding package.json or issue was provided closing.
